# Form implementation generated from reading ui file 'welcomeScreen.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1202, 800)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(680, -20, 531, 821))
        self.widget.setStyleSheet("background-image: url(./image/left_.jpg);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(-1, -1, 691, 801))
        self.widget_2.setStyleSheet("background-color:\"white\"")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.widget_3.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(80, 60, 71, 51))
        self.widget_4.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(80, 680, 81, 61))
        self.widget_5.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(10, 710, 101, 81))
        self.widget_6.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setGeometry(QtCore.QRect(530, 60, 71, 51))
        self.widget_7.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_7.setObjectName("widget_7")
        self.widget_8 = QtWidgets.QWidget(self.widget_2)
        self.widget_8.setGeometry(QtCore.QRect(570, 10, 111, 81))
        self.widget_8.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_8.setObjectName("widget_8")
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setGeometry(QtCore.QRect(530, 690, 71, 51))
        self.widget_9.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setGeometry(QtCore.QRect(570, 710, 111, 81))
        self.widget_10.setStyleSheet("background-image: url(./image/particles-geometric-art-line-dot-dip-pen_31941-148.webp);")
        self.widget_10.setObjectName("widget_10")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(90, 150, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 30pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(130, 200, 471, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(190, 240, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("text-align: center;")
        self.label_3.setObjectName("label_3")
        self.widget_11 = QtWidgets.QWidget(self.widget_2)
        self.widget_11.setGeometry(QtCore.QRect(280, 10, 131, 131))
        self.widget_11.setStyleSheet("border-image: url(./image/IIT_Guwahati_Logo.svg);")
        self.widget_11.setObjectName("widget_11")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(260, 360, 181, 61))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(48, 235, 255);\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"color:\"white\"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 500, 281, 61))
        self.pushButton_2.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(48, 235, 255);\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"color:\"white\"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to IIT G Desktop App"))
        self.label_2.setText(_translate("Dialog", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco"))
        self.label_3.setText(_translate("Dialog", "Lorem ipsum dolor sit amet, consectetur "))
        self.pushButton.setText(_translate("Dialog", "Login"))
        self.pushButton_2.setText(_translate("Dialog", "Create a new account ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
